default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("KIRPACHOV_COM_PORTFOLIO_DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("KIRPACHOV_COM_PORTFOLIO_DB_PASSWORD") { 'password' } %>

development:
  <<: *default
  database: kirpachov_com_portfolio_dev

test:
  <<: *default
  database: kirpachov_com_portfolio_test

production:
  <<: *default
  database: kirpachov_com_portfolio